name: Build
on: 
  push:
    paths:
      - sources/**
      - .github/workflows/**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Checkout submodules (pico-sdk)
      working-directory: ${{github.workspace}}
      run: git submodule update --init --recursive

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      id: arm-none-eabi-gcc-action
      with:
        release: 12.3.Rel1
    - run: arm-none-eabi-gcc --version

    - name: Create Build Environment for ILI9341
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{github.workspace}}
      run:  cmake -E make_directory ${{github.workspace}}/build-ili9341

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build-ili9341
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: PICO_SDK_PATH=../sources/Externals/pico-sdk PICO_TOOLCHAIN_PATH=${{steps.arm-none-eabi-gcc-action.outputs.path}} cmake ../sources -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_LCD=LCD_ST7789 

    - name: Set Build Number
      shell: bash
      env:
          GH_RUN_NUMBER: ${{ github.run_number }}
      run: echo "#define BUILD_COUNT \"$GH_RUN_NUMBER\"" > sources/Application/Model/BuildNumber.h

    - name: Get core count
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l

    - name: Build ILI9341
      working-directory: ${{github.workspace}}/build-ili9341
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel $(nproc)
    - uses: actions/upload-artifact@v4
      with:
        name: picoTracker_ili9341-uf2
        path: ${{github.workspace}}/build-ili9341/Adapters/picoTracker/main/picoTracker.uf2 

    - name: Create Build Environment for ST7789
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      working-directory: ${{github.workspace}}
      run:  cmake -E make_directory ${{github.workspace}}/build-st7789
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build-st7789
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: PICO_SDK_PATH=../sources/Externals/pico-sdk PICO_TOOLCHAIN_PATH=${{steps.arm-none-eabi-gcc-action.outputs.path}} cmake ../sources -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_LCD=LCD_ST7789 
  
    - name: Build ST7789
      working-directory: ${{github.workspace}}/build-st7789
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel $(nproc) 
    - uses: actions/upload-artifact@v4
      with:
        name: picoTracker_st7789-uf2
        path: ${{github.workspace}}/build-st7789/Adapters/picoTracker/main/picoTracker.uf2 